server:
  port: 8761

spring:
  application:
    name: discovery-service

logging:
  file:
    name: /home/agentic/uni-app-ui-demo/backend/logs/${spring.application.name}.log


eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
