server:
  port: 8087

spring:
  application:
    name: report-service
  logging:
    file:
      name: /home/agentic/uni-app-ui-demo/backend/logs/${spring.application.name}.log
  datasource:
    url: jdbc:postgresql://localhost:5432/report_db
    username: smg_admin
    password: smg_password_2025
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:19092
    consumer:
      group-id: report-service-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: false
    hostname: ${EUREKA_HOST:172.22.1.123}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
