spring:
  application:
    name: gateway-service
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
      discovery:
        group: DEFAULT_GROUP
