spring:
  application:
    name: subscription-service
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
      - optional:nacos:shared-datasource.yaml
      - optional:nacos:shared-kafka.yaml
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
